syntax = "proto3";

// https://github.com/grpc/grpc-go/tree/master/examples/helloworld
// https://github.com/taqucinco-com/chat_and_voip/blob/main/grpc/src/example.com/helloworld/helloworld.proto

package greeter;
option go_package = "google_stt_grpc/grpc/helloworld";

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloResponse) {}
  rpc SayHelloAgain(HelloRequest) returns (stream HelloResponse) {}
  rpc SayHelloToMany(stream HelloRequest) returns (HelloResponse) {}
  rpc SayChat(stream HelloRequest) returns (stream HelloResponse) {}
}

message HelloRequest {
  string name = 1;
}

message HelloResponse {
  string message = 1;
}
